version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: trisog-api
    container_name: trisog-api
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: yarn start